public with sharing class utils {
    
    public static final string monDay = 'Monday__c';
    public static final string tuedayDay = 'Tuesday__c';
    public static final string wenDay = 'Wednesday__c';
    public static final string thuDay = 'Thursday__c';
    public static final string friDay = 'Friday__c';
    public static final string satDay = 'Saturday__c';
    public static final string sunDay = 'Sunday__c';
    public static final string wPObjName = 'Working_Pattern__c';

}